### ISSUE TITLE
Support custom color maps configured in xcube server

### ISSUE THREAD

**Issue by forman** [xcube-dev/xcube-viewer#392]
Support the custom color maps that are published by xcube Server, see <https://github.com/xcube-dev/xcube/issues/1046>.

**Comment by konstntokas** [comment]
There is a little bug. For the categorical color map, color definition in RGB and RGBA does not work properly. The data is presented in the right color, but the color in the legend is not presented properly and exchanged by black. See example below: 

no_data should be red.

```
CustomColorMaps:
  - Identifier: s2_l2_scl
    Type: categorical
    Colors:
      - [ 0, [1, 0, 0], no data]
      - [ 1, yellow,  defective]
      - [ 2, black,   dark area pixels]
      - [ 3, gray,    cloud shadows]
      - [ 4, green,   vegetation]
      - [ 5, tan,     bare soils]
      - [ 6, blue,    water]
      - [ 7, "#aaaabb", clouds low prob ]
      - [ 8, "#bbbbcc", clouds medium prob]
      - [ 9, "#ccccdd", clouds high prob]
      - [10, "#ddddee", cirrus]
      - [11, "#ffffff", snow or ice]
```

![Screenshot from 2024-08-09 08-28-44](https://github.com/user-attachments/assets/1c071723-c1f4-458f-8cb6-60f3865a5f8f)
